version: '3'

services:
  gobarber-api:
    build: .
    container_name: gobarber-api
    volumes:
      - /usr/app
    ports:
      - '3333:3333'
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - gobarber-redis
      - gobarber-mongo
      - gobarber-postgres
    networks:
      - gobarber-network

  gobarber-redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    container_name: gobarber-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - gobarber-redis-data:/data
    networks:
      - gobarber-network

  gobarber-mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: gobarber-mongo
    environment:
      - MONGO_URL=${MONGO_URL}
    volumes:
      - gobarber-mongo-data:/data
    networks:
      - gobarber-network

  gobarber-postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    container_name: gobarber-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - gobarber-postgres-data:/data
    networks:
      - gobarber-network

volumes:
  gobarber-redis-data:
  gobarber-mongo-data:
  gobarber-postgres-data:

networks:
  gobarber-network:
    driver: bridge
